# Generated by Django 5.0.4 on 2024-05-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='atendida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cita',
            name='indicaciones',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='informe',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='receta',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
