# Generated by Django 5.0.4 on 2024-05-24 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_cita_atendida_cita_indicaciones_cita_informe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='receta',
            new_name='recipe',
        ),
    ]
