# Generated by Django 5.0.4 on 2024-05-16 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_customuser_telefono_appointment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disponibilidaddoctor',
            old_name='day',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='disponibilidaddoctor',
            old_name='end_time',
            new_name='hora_fin',
        ),
        migrations.RenameField(
            model_name='disponibilidaddoctor',
            old_name='start_time',
            new_name='hora_inicio',
        ),
    ]
