# Generated by Django 5.0.4 on 2024-05-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_receta_cita_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='falto',
            field=models.BooleanField(default=False),
        ),
    ]
